apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db

spec:
  type: ClusterIP # for internal communication
  ports:
  - name: "db-service"
    port: 5432
    targetPort: 5432 # this shouldn be db-pod port
  selector:
    app: db # this should be db-pod labels
