apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80 #container port
      targetPort: 80 #service port
      nodePort: 30004 #node port, range: 30000-32767
  selector:
    app: myapp+



kubectl create -f service-definition.yaml
kubectl get pods
kubectl get service/svc
kubectl get deployments
